services:
  web:
    build: .
    image: antonpas210/url-shortner:v1
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - short_url_data:/data

volumes:
  short_url_data:
